services:
  wpserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./wordpress-foro:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wpphp
    networks:
      - wordpress-network

  wpphp:  # <--- en minÃºsculas
    build:
      context: ./php
    volumes:
      - ./wordpress-foro:/var/www/html
    networks:
      - wordpress-network

  wpdatabase:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootp
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wordpress-network

volumes:
  mariadb_data:

networks:
  wordpress-network:
    driver: bridge
